# Generated by Django 5.0.3 on 2024-03-09 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat_data',
            name='name',
            field=models.CharField(choices=[('user', 'User'), ('admin', 'Admin')], max_length=40),
        ),
    ]
