# Generated by Django 5.0.3 on 2024-03-09 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversation', '0002_alter_chat_data_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat_data',
            name='name',
            field=models.CharField(choices=[('she', 'she'), ('me', 'me')], max_length=40),
        ),
    ]
